version: "3.9"
volumes:
  mysql_vol:

services:
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      TZ: UTC
      MYSQL_DATABASE: app1
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - mysql_vol:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', '127.0.0.1', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD' ]
      start_period: 3s
      interval: 3s
      timeout: 5s
      retries: 99

  webapp:
    image: webappimage
    build:
      context: .
      dockerfile: Dockerfile

    restart: always

    depends_on:
      db:
        condition: service_healthy

    ports:
      - "8000:8000"

    command: python -m manage runserver 0.0.0.0:8000
    environment:
      DJANGO_SETTINGS_MODULE: poetrydjango.settings_mysql
      MYSQL_DATABASE: app1
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_HOST: db

  testenv:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev

    command: /bin/bash
    depends_on:
      db:
        condition: service_healthy
    profiles:
      - optional
    environment:
      DJANGO_SETTINGS_MODULE: poetrydjango.settings_mysql
      MYSQL_DATABASE: app1
      MYSQL_USER: root
      MYSQL_PASSWORD: admin
      MYSQL_HOST: db

  migrate:
    image: webappimage
    command: python -m manage migrate
    depends_on:
      db:
        condition: service_healthy
    profiles:
      - optional
    environment:
      DJANGO_SETTINGS_MODULE: poetrydjango.settings_mysql
      MYSQL_DATABASE: app1
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_HOST: db

